### ISSUE TITLE
Notes don't persist on refresh 

### ISSUE THREAD

**Issue by LarmBee** [LarmBee/sticky-react-app#1]
I have code that's supposed to save to local storage which should make changes to the application persist but on refresh the notes reset to the default notes .
I am looking to have any change the user makes to persist, or any notes added to be saved and later viewed once opened again.

**Comment by dangvu0502** [comment]
Hi LarmBee.
I have just tested your deployed app.
As i see it work well with local storage.
It persist with change.

![image](https://user-images.githubusercontent.com/57172125/184783726-9285ae34-4b55-4c73-812f-7fd324c784b4.png)

**Comment by LarmBee** [comment]
Yeah I just noticed the same thing. For some reason on my local host as I
was testing before deployment it wasn't. Thank you for your time and
response though 😊
